In [1]:
import numpy as np
import sympy as sym

In [2]:
def Derivative(f,x,h=1e-4):
    return (f(x+h)-f(x-h))/(2*h)

In [3]:
def GetNewtonRaphson(f,df,xn,itmax = 100, precision=1e-10):
    
    error = 1
    it = 0
    
    while error > precision and it <= itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            
            #print('Division por cero')
            return "Not Found"
            
        it += 1
        xn = xn1
    
    if it == itmax:
        return "Not Found"
    else:
        return xn

In [4]:
def GetAllRoots(f, df, Newton_Raphson, n, h=0.1, tolerancia=6):
    
    Roots = np.array([])
    
    found = 0
    place = 0
    
    while found < n:
        
        xn_1 = place + h
        xn = place
        
        
        dn_1 = df(f, xn_1)
        dn = df(f, xn)

            
        if (f(xn) * f(xn_1)  <= 0.) or (dn * dn_1 <= 0.):
            zero_f = Newton_Raphson(f, df, xn_1)
            if zero_f != "Not Found":
                rzero_f = np.round(zero_f, tolerancia)
            
                same = False
            
                for root in Roots:
                    d = np.abs(root - rzero_f)
                    if d < 1e-5:
                        same = True
            
                if not same and rzero_f not in Roots:
                    Roots = np.append(Roots, rzero_f)
                    found += 1
        
        place += h
        
        if place > 100.:
            print("Mayor a 100")
            return Roots
    
    Roots.sort()
    
    return Roots

In [5]:
def GenerateNDegLaguerrePol(deg):
    x = sym.Symbol('x',real=True)
    n = sym.Symbol('n',real=True)
    
    f0 = sym.exp(x)/(sym.factorial(n))
    f1 = sym.exp(-x)*(x**n)
    F0 = f0.subs(n, deg)
    F1 = sym.diff(f1.subs(n, deg), x, deg)
    
    return sym.simplify(F0*F1)

In [6]:
def FindRootsUpToNLaguerre(n):
    x = sym.Symbol('x',real=True)
    
    Roots = []
    
    for i in range(1, n+1):
        f = GenerateNDegLaguerrePol(i)
        f = sym.lambdify([x], f, 'numpy')
        roots = GetAllRoots(f, Derivative, GetNewtonRaphson, i)
        Roots.append(roots)
        
    return Roots

In [7]:
Roots = FindRootsUpToNLaguerre(20)

In [8]:
def printNumRoots(Roots):
    for i in Roots:
        print(len(i))

In [9]:
printNumRoots(Roots)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [10]:
Roots

[array([1.]),
 array([0.585786, 3.414214]),
 array([0.415775, 2.29428 , 6.289945]),
 array([0.322548, 1.745761, 4.53662 , 9.395071]),
 array([ 0.26356 ,  1.413403,  3.596426,  7.08581 , 12.640801]),
 array([ 0.222847,  1.188932,  2.992736,  5.775144,  9.837467, 15.982874]),
 array([ 0.193044,  1.026665,  2.567877,  4.900353,  8.182153, 12.73418 ,
        19.395728]),
 array([ 0.17028 ,  0.903702,  2.251087,  4.2667  ,  7.045905, 10.758516,
        15.740679, 22.863132]),
 array([ 0.152322,  0.80722 ,  2.005135,  3.783474,  6.204957,  9.372985,
        13.466237, 18.833598, 26.374072]),
 array([ 0.137793,  0.729455,  1.808343,  3.401434,  5.552496,  8.330153,
        11.843786, 16.279258, 21.996586, 29.920697]),
 array([ 0.125796,  0.665418,  1.647151,  3.091138,  5.029284,  7.509888,
        10.605951, 14.431614, 19.178857, 25.217709, 33.497193]),
 array([ 0.115722,  0.611757,  1.51261 ,  2.833751,  4.599228,  6.844525,
         9.621317, 13.006055, 17.116855, 22.15109 , 28.487967, 37.

In [11]:
for i in Roots:
    print("Raices del polinomio de Laguerre de grado " + str(len(i)) + ":")
    for j in i:
        print(j)
    print("\n\n")

Raices del polinomio de Laguerre de grado 1:
1.0



Raices del polinomio de Laguerre de grado 2:
0.585786
3.414214



Raices del polinomio de Laguerre de grado 3:
0.415775
2.29428
6.289945



Raices del polinomio de Laguerre de grado 4:
0.322548
1.745761
4.53662
9.395071



Raices del polinomio de Laguerre de grado 5:
0.26356
1.413403
3.596426
7.08581
12.640801



Raices del polinomio de Laguerre de grado 6:
0.222847
1.188932
2.992736
5.775144
9.837467
15.982874



Raices del polinomio de Laguerre de grado 7:
0.193044
1.026665
2.567877
4.900353
8.182153
12.73418
19.395728



Raices del polinomio de Laguerre de grado 8:
0.17028
0.903702
2.251087
4.2667
7.045905
10.758516
15.740679
22.863132



Raices del polinomio de Laguerre de grado 9:
0.152322
0.80722
2.005135
3.783474
6.204957
9.372985
13.466237
18.833598
26.374072



Raices del polinomio de Laguerre de grado 10:
0.137793
0.729455
1.808343
3.401434
5.552496
8.330153
11.843786
16.279258
21.996586
29.920697



Raices del polinomio de 