In [266]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from tqdm import tqdm

In [267]:
d = np.linspace(-1,1,1000)
n = 20

In [268]:
E = sym.Symbol('E',real=True)
x = sym.Symbol('x',real=True)

In [270]:
PolHermit = []

for j in range(0,n+1):
    a = sym.exp(-(E**2))
    H = (-1)**j*sym.exp(E**2)*sym.diff(a,E,j,evaluate=True)
    

    #H2 = sym.diff(H2,E,n,evaluate=True)
    
    #H *= H2
    
    PolHermit.append(H)
    
PolHermit #aca tenemos los polinomios de hermite empezando desde n = 0 hasta n = 20

[1,
 2*E,
 4*E**2 - 2,
 -4*E*(3 - 2*E**2),
 16*E**4 - 48*E**2 + 12,
 -8*E*(-4*E**4 + 20*E**2 - 15),
 64*E**6 - 480*E**4 + 720*E**2 - 120,
 -16*E*(-8*E**6 + 84*E**4 - 210*E**2 + 105),
 256*E**8 - 3584*E**6 + 13440*E**4 - 13440*E**2 + 1680,
 -32*E*(-16*E**8 + 288*E**6 - 1512*E**4 + 2520*E**2 - 945),
 1024*E**10 - 23040*E**8 + 161280*E**6 - 403200*E**4 + 302400*E**2 - 30240,
 -64*E*(-32*E**10 + 880*E**8 - 7920*E**6 + 27720*E**4 - 34650*E**2 + 10395),
 4096*E**12 - 135168*E**10 + 1520640*E**8 - 7096320*E**6 + 13305600*E**4 - 7983360*E**2 + 665280,
 -128*E*(-64*E**12 + 2496*E**10 - 34320*E**8 + 205920*E**6 - 540540*E**4 + 540540*E**2 - 135135),
 16384*E**14 - 745472*E**12 + 12300288*E**10 - 92252160*E**8 + 322882560*E**6 - 484323840*E**4 + 242161920*E**2 - 17297280,
 -256*E*(-128*E**14 + 6720*E**12 - 131040*E**10 + 1201200*E**8 - 5405400*E**6 + 11351340*E**4 - 9459450*E**2 + 2027025),
 65536*E**16 - 3932160*E**14 + 89456640*E**12 - 984023040*E**10 + 5535129600*E**8 - 15498362880*E**6 + 1937

In [271]:
def Function(fun):
    return fun

In [272]:
def Derivative(fun,d,h=1e-4):
    return (fun(d+h)-fun(d-h))/(2*h)

In [273]:
def GetNewtonRaphson(f,df,xn,itmax = 100, precision=1e-5):
    
    error = 1
    it = 0
    
    while error > precision and it <= itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            
            error = np.abs(f(xn)/df(f,xn))
            
            #print(error)
            
        except ZeroDivisionError:
            
            print('Division por cero')
            
        it += 1
        xn = xn1
    
    if it == itmax:
        False
    else:
        return xn

In [274]:
Nr=[]
flag = False
for Function in PolHermit:
    if flag:
        Function = Function.subs(E,x)
        fun = sym.lambdify([x],Function,"numpy")
        Derivative(fun,d,h=1e-4)
        N = GetNewtonRaphson(fun,Derivative,1)
        Nr.append(N)
    else:
        flag = True

In [275]:
def GetAllRoots(x,tolerancia=8):
    
    Roots = np.array([])
    
    for i in x:
        
        root = GetNewtonRaphson(fun,Derivative,i)
        
        if root != False:
            
            croot = np.round(root, tolerancia)
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
        
    return Roots

In [276]:
#calculamos las primeras 20 raices

w = np.linspace(-1,1,100)
Rarr = []
flag = False
for Function in PolHermit:
    if flag:
        Function = Function.subs(E,x)
        fun = sym.lambdify([x],Function,"numpy")
        Roots = GetAllRoots(w)
        Rarr.append(Roots)
    else:
        flag = True
 

Rarr

[array([], dtype=float64),
 array([-0.70710678,  0.70710678]),
 array([-1.22474487, -0.        ,  1.22474487]),
 array([-1.65068012, -0.52464762,  0.52464762,  1.65068012]),
 array([-2.02018287, -0.95857246,  0.        ,  0.95857246,  2.02018287]),
 array([-2.35060497, -1.33584907, -0.43607741,  0.43607741,  1.33584907,
         2.35060497]),
 array([-2.65196136, -1.67355163, -0.81628788,  0.        ,  0.81628788,
         1.67355163,  2.65196136]),
 array([-2.93063742, -1.98165676, -1.15719371, -0.38118699,  0.38118699,
         1.15719371,  1.98165676,  2.93063742]),
 array([-3.1909932 , -2.26658058, -1.46855329, -0.72355102,  0.        ,
         0.72355102,  1.46855329,  2.26658058,  3.1909932 ]),
 array([-3.43615912, -2.53273167, -1.75668365, -1.03661083, -0.34290133,
         0.34290133,  1.03661083,  1.75668365,  2.53273167,  3.43615912]),
 array([-3.66847085, -2.02594802, -1.32655708, -0.65680957, -0.        ,
         0.65680957,  1.32655708,  2.02594802,  3.66847085]),
 array

In [277]:
#calculamos los pesos


Warr = []


for j in tqdm(range(1,n+1)):
    
    raiz = (Rarr[j-1])
    
    H = PolHermit[j-1]
    
    wActual = []
    
    for raices in raiz:
    
        Heval = H.subs(E,raices)
        
    
        try:
            W = (2**(j-1)*np.math.factorial(j)*((np.pi)**1/2))/((j**2)*(Heval**2))
        except:
            W = 0

        
        wActual.append(W)
        
    
    Warr.append(wActual)


100%|██████████| 20/20 [00:00<00:00, 62.53it/s] 


In [281]:
#para corroborar hacemos
for i in range(1,21):
    r,w = np.polynomial.hermite.hermgauss(i)
    print("N:" + str(i))
    print("Raiz:" + str(r))
    print("Peso:" + str(w))

N:1
Raiz:[0.]
Peso:[1.77245385]
N:2
Raiz:[-0.70710678  0.70710678]
Peso:[0.88622693 0.88622693]
N:3
Raiz:[-1.22474487  0.          1.22474487]
Peso:[0.29540898 1.1816359  0.29540898]
N:4
Raiz:[-1.65068012 -0.52464762  0.52464762  1.65068012]
Peso:[0.08131284 0.80491409 0.80491409 0.08131284]
N:5
Raiz:[-2.02018287 -0.95857246  0.          0.95857246  2.02018287]
Peso:[0.01995324 0.39361932 0.94530872 0.39361932 0.01995324]
N:6
Raiz:[-2.35060497 -1.33584907 -0.43607741  0.43607741  1.33584907  2.35060497]
Peso:[0.00453001 0.15706732 0.7246296  0.7246296  0.15706732 0.00453001]
N:7
Raiz:[-2.65196136 -1.67355163 -0.81628788  0.          0.81628788  1.67355163
  2.65196136]
Peso:[0.00097178 0.05451558 0.42560725 0.81026462 0.42560725 0.05451558
 0.00097178]
N:8
Raiz:[-2.93063742 -1.98165676 -1.15719371 -0.38118699  0.38118699  1.15719371
  1.98165676  2.93063742]
Peso:[1.99604072e-04 1.70779830e-02 2.07802326e-01 6.61147013e-01
 6.61147013e-01 2.07802326e-01 1.70779830e-02 1.99604072e-04]
N

In [282]:
#ahora podemos calcular la integral usando el metodo de hermite
suma = 0
for i in range(1,21):
    r,w = np.polynomial.hermite.hermgauss(i)
    R,W = r[0],w[0]
    fev = 2*R**2/((np.pi)**1/2)
    suma += fev*W
print(suma)    

1.5575694029371026
