In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
H = np.array([[1,2,-1],[1,0,1],[4,-4,5]])
x0 = np.array([1,1,1])

In [3]:
H

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [4]:
HI = np.linalg.inv(H)

In [5]:
def potenciaInversa(HI,x0,it=10000,acept=1e-14):
    dif = 100
    x = np.array([0,0,0])
    flag = False
    while not (np.allclose(x0,x,acept,acept)):
        if flag:
            x0 = x
        x = HI@x0/np.linalg.norm(x0)
        flag = True
    return x

In [6]:
res = potenciaInversa(HI,x0)

In [7]:
res

array([-0.40824829,  0.40824829,  0.81649658])

In [8]:
l = 1/np.linalg.norm(res)

In [9]:
l

0.9999999999999825

In [10]:
v = res/np.linalg.norm(res)

In [11]:
v

array([-0.40824829,  0.40824829,  0.81649658])