In [1]:
import numpy as np

In [2]:
def f1(x):
    return 6*x[0] - 2*np.cos(x[1]*x[2]) - 1

In [3]:
def f2(x):
    return 9*x[1] + np.sqrt(np.square(x[0]) + np.sin(x[2]) + 1.06) + 0.9

In [4]:
def f3(x):
    return 60*x[2] + 3*np.exp(-x[0]*x[1]) + 10*np.pi - 3.

In [5]:
def DerivateO4(f, x, component, h):
    H = np.zeros_like(x)
    H[component] += h
    return (-f(x+2*H) + 8*f(x+H) - 8*f(x-H) + f(x-2*H))/(12*h)

In [6]:
def DerivateO2(f, x, component, h):
    H = np.zeros_like(x)
    H[component] += h
    return (f(x+H) - f(x-H))/(2*h)

In [7]:
def Jacobian(F, x, O2 = False, h = 1e-2):
    J = np.zeros((len(F), len(x)))
    for i in range(len(F)):
        for j in range(len(x)):
            if not O2:
                J[i][j] = DerivateO4(F[i], x, j, h)
            else:
                J[i][j] = DerivateO2(F[i], x, j, h)
                
    return J

In [8]:
F = (f1, f2, f3)
x = np.array(([0.5, 0.5, 0.5]))

In [9]:
JO4 = Jacobian(F, x)
JO4

array([[ 6.        ,  0.24740396,  0.24740396],
       [ 0.37377753,  9.        ,  0.32802064],
       [-1.16820117, -1.16820117, 60.        ]])

In [10]:
JO2 = Jacobian(F, x, O2 = True)
JO2

array([[ 6.        ,  0.24740293,  0.24740293],
       [ 0.37376854,  9.        ,  0.32801836],
       [-1.16820604, -1.16820604, 60.        ]])

Sean h0 y h1 los valores de h para la derivada de orden 4 y orden 2 respectivamente. Si queremos que los errores de ambos métodos sean iguales, entonces podemos establecer la siguiente igualdad:

(h0)^4 = (h1)^2    =>    (h0)^2 = h1

Si establecemos h0 = 0.01 (como en las instrucciones del problema), tenemos que:

h1 = 0.0001

A continuación, verificamos este resultado:

In [11]:
JO2_2 = Jacobian(F, x, O2 = True, h = 1e-4)
JO2_2

array([[ 6.        ,  0.24740396,  0.24740396],
       [ 0.37377753,  9.        ,  0.32802064],
       [-1.16820118, -1.16820118, 60.        ]])

Arriba, podemos apreciar como el Jacobiano obtenido con h = 0.0001 en la derivada de orden 2 es casi idéntico al Jacobiano obtenido con h = 0.01 en la derivada de orden 4 (salvo por una diferencia de 1.*10^-8, en las entradas [3,1] y [3,2]).