In [1]:
import numpy as np

In [2]:
def findLargest(M):
    largest_num = -np.inf
    largest_pos = np.array(([0, 0]))
    for i in range(len(M[:,])):
        for j in range(len((M[0,:]))):
            if i != j:
                if np.abs(M[i, j]) > largest_num:
                    largest_num = np.absolute(M[i, j])
                    largest_pos[0] = i
                    largest_pos[1] = j
                    
    return largest_pos

In [3]:
def findTheta(M, pos):
    i = pos[0]
    j = pos[1]
    mij = M[i, j]
    mii = M[i, i]
    mjj = M[j, j]
    
    if mii == mjj:
        return np.pi/4
    else:
        return (0.5)*np.arctan((2*mij)/np.absolute((mii - mjj)))

In [4]:
def createMatrixR(M, pos):
    R = np.identity(len(M[:,]))
        
    theta = findTheta(M, pos)
    i = pos[0]
    j = pos[1]
    
    R[i, j] = np.sin(theta)
    R[j, i] = -np.sin(theta)
    R[i, i] = np.cos(theta)
    R[j, j] = np.cos(theta)
    
    return R

In [5]:
def checkDiagonal(M):
    for i in range(len(M[:,])):
        for j in range(len((M[0,:]))):
            if i != j:
                if M[i, j] != 0:
                    return False
            
    return True

In [6]:
def cleanMatrix(M, c = 1e-12):
    for i in range(len(M[:,])):
        for j in range(len((M[0,:]))):
            if i != j:
                if np.abs(M[i, j]) < c:
                    M[i, j] = 0.
                    
    return M

In [7]:
A = np.array(([4., 1., 1.], [1., 3., 2.], [1., 2., 5.]))
A2 = np.copy(A)
print(A)

R = np.identity(len(A[:,]))

max_it = 100
it = 0
diag = False
while not diag and it < max_it:
    pos = findLargest(A)
    R_actual = createMatrixR(A, pos)
    R = np.matmul(R, R_actual)
    R_inv = np.linalg.inv(R_actual)
    A = np.matmul(R_inv, np.matmul(A, R_actual))
    A = cleanMatrix(A)
    diag = checkDiagonal(A)
        
    it += 1

print(it)
A

[[4. 1. 1.]
 [1. 3. 2.]
 [1. 2. 5.]]
17


array([[6.89510652, 0.        , 0.        ],
       [0.        , 1.70759841, 0.        ],
       [0.        , 0.        , 3.39729507]])

Vector Propio de 6.89510652:

In [8]:
r1 = np.array(([1., 0., 0.]))
v1 = np.matmul(R, r1)
if v1[0] < 0:
    v1 = -v1
(1/np.linalg.norm(v1))*v1

array([0.43170413, 0.49725362, 0.75257583])

Vector Propio de 1.70759841:

In [9]:
r2 = np.array(([0., 1., 0.]))
v2 = np.matmul(R, r2)
if v2[0] < 0:
    v2 = -v2
(1/np.linalg.norm(v2))*v2

array([ 0.17059871, -0.86427949,  0.47319874])

Vector Propio de 3.39729507:

In [10]:
r3 = np.array(([0., 0., 1.]))
v3 = np.matmul(R, r3)
if v3[0] < 0:
    v3 = -v3
(1/np.linalg.norm(v3))*v3

array([ 0.88573564, -0.07589338, -0.45794385])

In [11]:
np.linalg.eig(A2)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))